### ISSUE TITLE
Disabling images — webextension, or not?

### ISSUE THREAD

**Issue by ffoodd** [ffoodd/a11y.css-webextension#17]
Doable with CSS:
```css
img {
    visibility: hidden;
}

* {
    background-image: unset !important;
}
```

But how would we activate this?
